config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
  end

  def about
  end

  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Signup"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    # RAILS_DEFAULT_LOGGER.info ("in ApplicationHelper title")
    base_title = "Ruby on rails tutorial sample app"
    if @title.nil?
    base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<li>
				<a href="http://news.railstutorial.org/">News</a>
			</li>
			<li>
				<a href="http://www.railstutorial.org/">Rails tutorial</a>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path%>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "Help", help_path %>
			</li>
			<li>
				<%= link_to "Sign in", signup_path %>
			</li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen.css', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print.css', :media => 'print' %> <!-- [if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie' %>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>

		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages # about </h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1> Help here></h1>
<p>
	come get some help
</p>

app/views/pages/home.html.erb
<h1> Sample App </h1>
<p>
	this is the home page of the sample app
</p>
<%= link_to "Sign up now", '#', :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>